{% set version = "2.0.7" %}

package:
  name: bob.sp
  version: {{ version }}

source:
  fn: bob.sp-{{ version }}.zip
  url: https://pypi.io/packages/source/b/bob.sp/bob.sp-{{ version }}.zip
  md5: 6ea7680028dcb01f386044aa130fac94

build:
  number: 0
  skip: true  # [win]
  script: python -B setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - toolchain
    - setuptools
    - bob.extension >2.0.4
    - bob.blitz
    - bob.core
    - cmake
    - pkg-config

  run:
    - python
    - bob.extension >2.0.4
    - bob.blitz
    - bob.core

test:
  imports:
    - bob
    - bob.sp

  commands:
    - nosetests -sv bob.sp

  requires:
    - nose

about:
  home: https://www.idiap.ch/software/bob/
  license: Modified BSD License (3-clause)
  summary: Bob's signal processing utilities

extra:
  recipe-maintainers:
    - 183amir
